# Generated by Django 5.0 on 2023-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ManyToManyField(blank=True, related_name='prod_image', to='products.image'),
        ),
    ]
