# Generated by Django 5.0 on 2023-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproduct',
            name='products',
            field=models.ManyToManyField(related_name='selected_by_users', to='products.product'),
        ),
    ]
